### PR TITLE
Webviewtypes

### PR DESCRIPTION
**Pull request by KaviHarjani**
These are different methods of enabling webviews, the one where all works is inAppChromeSafari

### CODE REVIEW

**Comment by KaviHarjani** [comment]
Hey @manujagobind Can you try out this branch, I cloned a repo which was experimenting with different forms of webviews minor changes to try it out with screener, only ChromeSafari inapp seems download from export to excel and also razorpay

**Comment by manujagobind** [comment]
> Hey @manujagobind Can you try out this branch, I cloned a repo which was experimenting with different forms of webviews minor changes to try it out with screener, only ChromeSafari inapp seems download from export to excel and also razorpay

Hey @KaviHarjani - excellent.

Any way we can remove the top and bottom bars in this?

image

Also, what happens when the user's device doesn't have either Chrome or Safari?

**Comment by KaviHarjani** [comment]
Hey @manujagobind exploring the bottom and nav bar thing today, maybe doable through TWA also I don't know what would happen if no Chrome or Safari

**Comment by manujagobind** [comment]
Closing this experiment branch for now.

**Pull request closed without merging**
